# Permission for Staff Chat
perms: "chat.staffchat"

# Use ยง for colors!
entersc: "You have joined staff chat! Please run /sc to leave it!"
leavesc: "You have left staff chat! Please run /sc to join it again!"

